# Generated by Django 2.1.2 on 2018-11-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181123_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterArtisans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisan_name', models.CharField(max_length=150)),
                ('artisan_email', models.EmailField(max_length=254)),
                ('artisan_password', models.CharField(max_length=150)),
                ('artisan_repeat_password', models.CharField(max_length=150)),
                ('artisan_phone', models.IntegerField()),
                ('state_of_origin', models.CharField(choices=[('AB', 'Abia'), ('AD', 'Adamawa'), ('AN', 'Anambra'), ('BU', 'Bauchi'), ('BE', 'Benue')], max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email is incorrect or Already exists'}, max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='registerartisans',
            unique_together={('artisan_email', 'artisan_phone')},
        ),
    ]
